# Generated by Django 5.0.3 on 2024-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=225)),
                ('Course_description', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('course_image', models.ImageField(upload_to='course.png')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
