# Generated by Django 5.0.3 on 2024-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_course_description_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='course'),
        ),
    ]
